"""
bronze/ingest_bronze.py
-----------------------
Bronze layer validation task.

Responsibility:
  - Validate that expected source files are present in their data directories
  - Log file sizes (cheap metadata check)
  - Never modify the file content — bronze = raw as-is on disk

In this project, bronze is the raw files sitting in:
  - data/land_registry/pp-complete.csv
  - data/boe/Bank of England  Database.csv
  - data/mlar/mlar_1_*.csv  (generated by mlar_parser.py)

This script is called by the Airflow DAG as an early validation step.
"""

import logging
from pathlib import Path

from utils.config import (
    LAND_REGISTRY_PATH, LAND_REGISTRY_FILENAME,
    BOE_PATH, BOE_FILENAME,
    MLAR_PATH, MLAR_1_21_FILENAME, MLAR_1_32_FILENAME, MLAR_1_33_FILENAME,
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Files we expect to find — maps a logical name to (directory, filename)
EXPECTED_FILES = {
    "Land Registry (full)": (LAND_REGISTRY_PATH, LAND_REGISTRY_FILENAME),
    "Bank of England":      (BOE_PATH,           BOE_FILENAME),
    "MLAR 1.21":            (MLAR_PATH,          MLAR_1_21_FILENAME),
    "MLAR 1.32":            (MLAR_PATH,          MLAR_1_32_FILENAME),
    "MLAR 1.33":            (MLAR_PATH,          MLAR_1_33_FILENAME),
}

# These must exist or the pipeline cannot proceed
CRITICAL_FILES = {"Land Registry (full)", "Bank of England"}


def validate_bronze() -> dict:
    """
    Check that all expected source files exist and have non-zero size.
    Returns a summary dict: {logical_name: size_bytes or -1 if missing}.
    Raises FileNotFoundError if any critical file is missing.
    """
    summary = {}

    for name, (directory, filename) in EXPECTED_FILES.items():
        path = Path(directory) / filename

        if not path.exists():
            summary[name] = -1
            if name in CRITICAL_FILES:
                raise FileNotFoundError(
                    f"Critical source file missing: {path}. "
                    f"Please download and place it in {directory}/."
                )
            else:
                logger.warning(
                    "Optional file not found: %s — pipeline will skip this source. "
                    "Run mlar_parser.py first if MLAR CSVs are missing.",
                    path,
                )
            continue

        size = path.stat().st_size
        if size == 0:
            raise ValueError(f"Source file is empty (0 bytes): {path}")

        summary[name] = size
        logger.info(
            "Validated: %s → %s (%.1f MB)",
            name, path, size / 1_048_576,
        )

    logger.info("Bronze validation complete. %d file(s) checked.", len(summary))
    return summary


if __name__ == "__main__":
    validate_bronze()
